<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzaskfw\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzaskfw/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWzaskfw.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWzaskfw\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWzaskfw\appProdProjectContainer([
    'container.build_hash' => 'Wzaskfw',
    'container.build_id' => '891c5c5c',
    'container.build_time' => 1625227275,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzaskfw');
